version: "3"

services:
  db:
    image: mariadb/server:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydish
    ports:
      - "3306:3306"
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/
